# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "CTRL+Shift: Writing practice at the dawn of the digital era"
email: dbecker@uidaho.edu
description: > # this means to ignore newlines until "baseurl:"
 A series of interviews on how poets' writing practices changed with the advent of the personal computer and digital era. Interviews were conducted by Devin Becker with 11 prominent poets, including Amy Gerstler, Robert Pinsky, Michael Ryan, Stephanie Strickland, Robert Wrigley, Nance Van Winckel, K. Silem Mohammad, James McMichael, Louise Glück, Bruce Beasley, and Rae Armantrout. Interviews were analyzed, visualized and messed around with by Devin Becker, Corey Oglesby, and Lauren Westerfield.
keywords: computers, paper, typewriters, revision, poetry, poets, writing, writing practice, oral history, interviews, poets, Amy Gerstler, Robert Pinsky, Michael Ryan, Stephanie Strickland, Robert Wrigley, Nance Van Winckel, K. Silem Mohammad, James McMichael, Louise Glück, Bruce Beasley, Rae Armantrout, digital era, personal computer
github_username: ctrlshifty

url: 

collections:
  processes:
    output: true
  questions:
      output: true
      permalink: /analyses/:collection/:name
  cachefiles:
      output: true
  interviews:
      output: true
  ohms:
      output: true
  videos:
      output: true
      permalink: /flotsam/:collection/:name
  photos:
      output: true
      permalink: /flotsam/:collection/:name
  respondents:
      output: true
      permalink: /analyses/:collection/:name
  tools:
      output: true
      permalink: /analyses/:collection/:name
  genpoems:
      output: true
      permalink: /flotsam/:collection/:name
  transcripts:
      output: true
      permalink: /interviews/:collection/:name

defaults:
  - scope:
      type: processes
    values:
      layout: process
  - scope:
      type: interviews
    values:
      layout: interview
  - scope:
      type: questions
    values:
      layout: question
  - scope:
      type: cachefiles
    values:
      layout: null
  - scope:
      type: genpoems
    values:
      layout: poems
  - scope:
      type: videos
    values:
      layout: video
  - scope:
      type: photos
    values:
      layout: photo
  - scope:
      type: textviz
    values:
      layout: textviz
  - scope:
      type: ohms
    values:
      layout: ohms
  - scope:
      type: tools
    values:
      layout: tool
  - scope:
      type: respondents
    values:
      layout: respondent
  - scope:
      type: transcripts
    values:
      layout: transcript
      


# Build settings
markdown: kramdown
